local addon = _G.LunaUITweaks
local function Setup(panel, tab)
    local H = addon.ConfigHelpers
    local title=panel:CreateFontString(nil,"OVERLAY","GameFontNormalHuge")
    title:SetPoint("TOPLEFT",16,-16); title:SetText("Gear Review")
    local desc=panel:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall")
    desc:SetPoint("TOPLEFT",20,-58); desc:SetWidth(490); desc:SetJustifyH("LEFT")
    desc:SetText("Review usable bag gear at the same or higher item level than equipped gear. Independent of bag addons. Item level is not an upgrade score; weapons require manual review.")
    local function Check(key,text,y)
        local b=CreateFrame("CheckButton",nil,panel,"ChatConfigCheckButtonTemplate")
        b:SetPoint("TOPLEFT",20,y); b.Text:SetText(text)
        b:SetScript("OnClick",function(self)
            UIThingsDB.gearReview[key]=not not self:GetChecked()
            addon.GearReview.UpdateSettings()
            H.UpdateModuleVisuals(panel,tab,UIThingsDB.gearReview.enabled)
        end)
        panel:HookScript("OnShow",function() b:SetChecked(UIThingsDB.gearReview[key]) end)
        b:SetChecked(UIThingsDB.gearReview[key])
    end
    Check("enabled","Enable Gear Review",-126)
    Check("notify","Show new-gear notices only in resting areas",-164)
    H.CreateSectionHeader(panel,"Review your gear",-220)
    local open=CreateFrame("Button",nil,panel,"UIPanelButtonTemplate")
    open:SetPoint("TOPLEFT",20,-258); open:SetSize(170,28); open:SetText("Open Gear Review")
    open:SetScript("OnClick",addon.GearReview.ToggleWindow)
    local help=panel:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall")
    help:SetPoint("TOPLEFT",20,-308); help:SetWidth(490); help:SetJustifyH("LEFT")
    help:SetText("Open anytime out of combat with /lunagear.\n\nIgnore applies to that physical item on this character and persists through reloads. Enable Show ignored in the window to restore it.\n\nRings and trinkets compare against the lower equipped slot. Equip buttons use that slot; Blizzard still handles binding confirmations and equipment restrictions.")
    H.UpdateModuleVisuals(panel,tab,UIThingsDB.gearReview.enabled)
end
LunaUITweaksAPI.RegisterConfigPanel("gearReview","Gear Review","Interface\\Icons\\INV_Chest_Plate04",Setup)
